run1:	
	g++ performance.cpp -o performance && g++ mip.cpp -o mip && ./mip performance 1

run2:	
	g++ performance.cpp -o performance && g++ mip.cpp -o mip && ./mip performance 2

run3:	
	g++ performance.cpp -o performance && g++ mip.cpp -o mip && ./mip performance 3

run4:	
	g++ performance.cpp -o performance && g++ mip.cpp -o mip && ./mip performance 4

run5:	
	g++ performance.cpp -o performance && g++ mip.cpp -o mip && ./mip performance 5

run6:	
	g++ performance.cpp -o performance && g++ mip.cpp -o mip && ./mip performance 6

run7:	
	g++ performance.cpp -o performance && g++ mip.cpp -o mip && ./mip performance 7

run8:	
	g++ performance.cpp -o performance && g++ mip.cpp -o mip && ./mip performance 8

run9:
	g++ performance.cpp -o performance && g++ mip.cpp -o mip && ./mip performance 9

run10:
	g++ performance.cpp -o performance && g++ mip.cpp -o mip && ./mip performance 10

