run1:	
	g++ performance.cpp -o performance && g++ mip.cpp -o mip && ./mip performance 1

run2:	
	g++ performance.cpp -o performance && g++ mip.cpp -o mip && ./mip performance 2

run4:	
	g++ performance.cpp -o performance && g++ mip.cpp -o mip && ./mip performance 4

run8:	
	g++ performance.cpp -o performance && g++ mip.cpp -o mip && ./mip performance 8
